# This is the general configuration file of the OGB framework evaluation

# Basic training options
seed: 1234
early_stopping_wait: 3
early_stop_metric: 'val_loss'
gpus: -1
batch_size: 1

# Flags to control the intialization of the embeddings
use_dropout: True
use_normalization: True

# Other options
defaults:
    - optimizer: myOptimizer
    - experiment: ogbg-molhiv
    - model: vanilla_gat